# frozen_string_literal: true

module CddlMap
  class Diagram
    def self.render(manifest)
      new(manifest).render
    end

    def self.markdown(manifest)
      "<!-- Generated by cddl-map diagram --markdown; do not edit. -->\n\n" \
        "```mermaid\n#{render(manifest)}```\n"
    end

    def initialize(manifest)
      @manifest = manifest
      @document_nodes = node_ids(manifest.documents, "document")
      @cddl_nodes = node_ids(manifest.cddl, "cddl")
      @edn_nodes = node_ids(manifest.edn, "edn")
    end

    def render
      lines = ["flowchart LR"]
      render_documents(lines)
      lines << ""
      render_cddl_edges(lines)
      render_edn_edges(lines)
      lines << ""
      render_styles(lines)
      lines.join("\n") + "\n"
    end

    private

    def node_ids(collection, prefix)
      collection.keys.each_with_index.to_h do |name, index|
        [name, "#{prefix}_#{index + 1}"]
      end
    end

    def render_documents(lines)
      @manifest.documents.each do |name, document|
        label = "#{escape(name)}<br/>#{escape(document.source_identity)}"
        lines << %(  subgraph #{@document_nodes.fetch(name)}["#{label}"])
        lines << "    direction TB"
        render_document_cddl(lines, name)
        render_document_edn(lines, name)
        lines << "  end"
      end
    end

    def render_document_cddl(lines, document)
      @manifest.cddl.each do |name, spec|
        next unless spec.document == document

        lines << %(    #{@cddl_nodes.fetch(name)}["CDDL: #{escape(name)}"])
      end
    end

    def render_document_edn(lines, document)
      @manifest.edn.each do |name, spec|
        next unless spec.document == document

        label = "EDN: #{escape(name)}<br/>entry: #{escape(spec.entry_rule)}" \
                "<br/>expect: #{escape(spec.expect)}"
        lines << %(    #{@edn_nodes.fetch(name)}["#{label}"])
      end
    end

    def render_cddl_edges(lines)
      @manifest.cddl.each do |name, spec|
        source = @cddl_nodes.fetch(name)
        spec.depends_on.each do |dependency|
          lines << %(  #{source} -->|"depends_on"| #{@cddl_nodes.fetch(dependency)})
        end
        spec.imports.each do |imported|
          label = imported.rules ? "imports: #{imported.rules.join(', ')}" : "imports"
          lines << %(  #{source} -.->|"#{escape(label)}"| #{@cddl_nodes.fetch(imported.cddl)})
        end
      end
    end

    def render_edn_edges(lines)
      @manifest.edn.each do |name, spec|
        source = @edn_nodes.fetch(name)
        spec.cddl.each do |root|
          label = "validates against: #{spec.entry_rule}"
          lines << %(  #{source} -->|"#{escape(label)}"| #{@cddl_nodes.fetch(root)})
        end
      end
    end

    def render_styles(lines)
      lines << "  classDef cddl fill:#ddf4ff,stroke:#0969da,color:#1f2328;"
      lines << "  classDef accepted fill:#dafbe1,stroke:#1a7f37,color:#1f2328;"
      lines << "  classDef rejected fill:#ffebe9,stroke:#cf222e,color:#1f2328;"
      lines << "  classDef skipped fill:#fff8c5,stroke:#9a6700,color:#1f2328;"
      lines << "  class #{@cddl_nodes.values.join(',')} cddl;"
      %w[accept reject skip].each do |expectation|
        nodes = @manifest.edn.filter_map do |name, spec|
          @edn_nodes.fetch(name) if spec.expect == expectation
        end
        next if nodes.empty?

        style = { "accept" => "accepted", "reject" => "rejected", "skip" => "skipped" }
        lines << "  class #{nodes.join(',')} #{style.fetch(expectation)};"
      end
    end

    def escape(value)
      value.to_s
        .gsub("&", "&amp;")
        .gsub("<", "&lt;")
        .gsub(">", "&gt;")
        .gsub('"', "&quot;")
        .gsub(/\s+/, " ")
    end
  end
end
