# frozen_string_literal: true

require "fileutils"
require "tempfile"
require "yaml"

module CddlMap
  class Lockfile
    VERSION = 1

    def self.default_path(manifest_path)
      if manifest_path.match?(/\.ya?ml\z/i)
        manifest_path.sub(/\.ya?ml\z/i, ".lock.yml")
      else
        "#{manifest_path}.lock.yml"
      end
    end

    def self.load(path, required: false)
      unless File.file?(path)
        if required
          raise Error.new(
            "lockfile #{path} does not exist",
            code: "lock_missing",
            path: path
          )
        end
        return nil
      end

      data = YAML.safe_load(
        File.binread(path),
        permitted_classes: [],
        permitted_symbols: [],
        aliases: false
      )
      unless data.is_a?(Hash) && data["version"] == VERSION &&
             data["documents"].is_a?(Hash) && data["selections"].is_a?(Hash)
        raise Error.new(
          "lockfile #{path} is not a version #{VERSION} cddl-map lockfile",
          code: "lock_format",
          path: path
        )
      end
      data
    rescue Errno::EACCES, Errno::EISDIR => e
      raise Error.new(
        "cannot read lockfile #{path}: #{e.message}",
        code: "lock_io",
        path: path
      )
    rescue Psych::Exception => e
      raise Error.new(
        "invalid YAML in lockfile #{path}: #{e.message}",
        code: "lock_format",
        path: path
      )
    end

    def self.build(documents, selections)
      {
        "version" => VERSION,
        "documents" => documents.keys.sort.to_h do |id|
          document = documents.fetch(id)
          [id, { "source" => document.source }]
        end,
        "selections" => selections.keys.sort.to_h do |key|
          selection = selections.fetch(key)
          [
            key,
            {
              "document" => selection.fetch(:document),
              "selector" => deep_plain(selection.fetch(:selector)),
              "blocks" => selection.fetch(:matches).map(&:lock_entry)
            }
          ]
        end
      }
    end

    def self.verify!(expected, actual, path:)
      differences = diff(expected, actual)
      return if differences.empty?

      raise Error.new(
        "resolved documents or selectors differ from #{path}",
        code: "lock_drift",
        path: path,
        differences: differences.first(25)
      )
    end

    def self.write(path, data)
      directory = File.dirname(File.expand_path(path))
      FileUtils.mkdir_p(directory)
      Tempfile.create([".cddl-map-lock-", ".tmp"], directory) do |file|
        file.binmode
        file.write("# Generated by cddl-map; update with --update-lock.\n")
        file.write(YAML.dump(data))
        file.flush
        file.fsync
        File.rename(file.path, path)
      end
    rescue SystemCallError => e
      raise Error.new(
        "cannot write lockfile #{path}: #{e.message}",
        code: "lock_io",
        path: path
      )
    end

    def self.diff(expected, actual, location = "$")
      if expected.is_a?(Hash) && actual.is_a?(Hash)
        (expected.keys | actual.keys).sort.flat_map do |key|
          child = "#{location}.#{key}"
          if !expected.key?(key)
            ["#{child}: added #{actual[key].inspect}"]
          elsif !actual.key?(key)
            ["#{child}: missing (was #{expected[key].inspect})"]
          else
            diff(expected[key], actual[key], child)
          end
        end
      elsif expected.is_a?(Array) && actual.is_a?(Array)
        length = [expected.length, actual.length].max
        (0...length).flat_map do |index|
          child = "#{location}[#{index}]"
          if index >= expected.length
            ["#{child}: added #{actual[index].inspect}"]
          elsif index >= actual.length
            ["#{child}: missing (was #{expected[index].inspect})"]
          else
            diff(expected[index], actual[index], child)
          end
        end
      elsif expected == actual
        []
      else
        ["#{location}: expected #{expected.inspect}, got #{actual.inspect}"]
      end
    end

    def self.deep_plain(value)
      case value
      when Hash
        value.to_h { |key, item| [key.to_s, deep_plain(item)] }
      when Array
        value.map { |item| deep_plain(item) }
      else
        value
      end
    end
    private_class_method :deep_plain
  end
end
